# Generated by Django 3.2.8 on 2021-10-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('mv_name', models.CharField(max_length=128)),
                ('mv_country', models.CharField(choices=[('中国', 'Zh'), ('美国', 'Us'), ('日本', 'Jp')], default='中国', max_length=36)),
                ('mv_mtype', models.CharField(choices=[('喜剧', 'Comedy')], default='喜剧', max_length=24)),
                ('mv_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('tv_name', models.CharField(max_length=128)),
                ('tv_country', models.CharField(choices=[('中国', 'Zh'), ('美国', 'Us'), ('日本', 'Jp')], default='中国', max_length=36)),
                ('tv_mtype', models.CharField(choices=[('喜剧', 'Comedy')], default='喜剧', max_length=24)),
                ('tv_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('e_title', models.CharField(max_length=256)),
                ('e_url', models.CharField(max_length=256)),
                ('tv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tvseries')),
            ],
        ),
    ]
