# Generated by Django 3.2.8 on 2021-10-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoParser',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36, verbose_name='名称')),
                ('p_url', models.CharField(max_length=128, verbose_name='链接地址')),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='e_title',
            field=models.CharField(max_length=256, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='e_url',
            field=models.CharField(max_length=256, verbose_name='播放链接'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_country',
            field=models.CharField(choices=[('中国', 'Zh'), ('美国', 'Us'), ('日本', 'Jp')], default='中国', max_length=36, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_description',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_mtype',
            field=models.CharField(choices=[('喜剧', 'Comedy')], default='喜剧', max_length=24, verbose_name='影片类型'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tv_country',
            field=models.CharField(choices=[('中国', 'Zh'), ('美国', 'Us'), ('日本', 'Jp')], default='中国', max_length=36, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tv_description',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tv_mtype',
            field=models.CharField(choices=[('喜剧', 'Comedy')], default='喜剧', max_length=24, verbose_name='影片类型'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tv_name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
    ]
