# Generated by Django 3.2.8 on 2021-10-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20211018_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='tv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tvseries', verbose_name='电视剧'),
        ),
    ]
