# Generated by Django 3.2.8 on 2021-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_episode_tv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mv_name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
    ]
