# Generated by Django 3.2.8 on 2021-10-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20211019_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='movies',
            field=models.ManyToManyField(to='videos.Movie', verbose_name='电影集'),
        ),
        migrations.CreateModel(
            name='MovieRelations',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.movie')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.movieseries')),
            ],
        ),
    ]
