# Generated by Django 3.2.8 on 2021-10-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20211019_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRelations',
        ),
    ]
